### ISSUE TITLE
10x CRAM to fastq?

### ISSUE THREAD

**Issue by PetrNguyen** [darwintreeoflife/darwintreeoflife.data#2]
Hi, could you please advise me how could I turn 10x data released as CRAM files into fastq which I could feed to supernova? Thanks for your time. Cheers, Petr

**Comment by KamilSJaron** [comment]
Hi Petr,

I think samtools should be able to do the trick... I would try something like

```
samtools fastq -1 R1.fastq -2 R2.fastq INPUT.cram
```

**Comment by PetrNguyen** [comment]
Hi Kamil,
what about third fastq file with sample information? Should I hack it somehow? 
Cheers

**Comment by KamilSJaron** [comment]
Uh, I was not even aware there is the third fastq file with sample info. Honestly, I have no idea.  My suggestion will be probably useless then

**Comment by mcshane** [comment]
This is what we run at Sanger:
```
samtools fastq -@4 -i -1 ${sample}_S${tag}_L%03s_R1_001.fastq.gz -2 ${sample}_S${tag}_L%03s_R2_001.fastq.gz \
--i1 ${sample}_S${tag}_L%03s_I1_001.fastq.gz --index-format i8 ${lane}.cram
```

**Comment by PetrNguyen** [comment]
Thanks!
