### ISSUE TITLE
up-to-date equivalent of data.tsv files for Tree of Life data?

### ISSUE THREAD

**Issue by avilella** [darwintreeoflife/darwintreeoflife.data#3]
Hi all,

I am trying to augment the available sequences for a handful of specific vertebrate/mammalian proteins and my idea was to use 'diamond blastx' to blast fastq data from the VGP / Tree of Life raw reads.

I've seen the darwintreeoflife.data repo, which says it's discontinued, and this seems to be the one containing more up to date information (up to current month). Is there a way to get a long list of http bam or cram URLs for all the vertebrates/mammalian genomes in the Tree of Life project? E.g.

Something equivalent to the "*data.tsv" files in darwintreeoflife.data but up-to-date with current freshly generated data. Thanks in advance.

```
find darwintreeoflife.data/ -name "*data.tsv" | sort -V | xargs cat | grep -e 'bam$' -e 'cram$'
```

**Comment by mcshane** [comment]
Have a look at the DToL portal (https://portal.darwintreeoflife.org/). They should be able to help with pointers on easy ways to access the available raw data. All raw data and assemblies are going into the ENA as soon as ready under this BioProject: https://www.ebi.ac.uk/ena/browser/view/PRJEB40665

**Comment by avilella** [comment]
Looking at the genomeark aws s3 bucket, it turns out it's got each species
as a subfolder, so I can use Wikipedia to check if they are within my
taxonomic range, then download the data from there:

```
aws s3 --no-sign-request ls s3://genomeark/species/
```
Thanks!
